### PR TITLE
Code for back-filling ovl_sushi bucket

### PR DESCRIPTION
**Pull request by deepsp94**
@mikeyrf, The script "backfill_influx_bulk.py" is just a quickly hacked together. These are the steps it goes through:

1. Read the last 30 days of data from your ovl_sushi bucket
2. Fix token0/1 names where required
3. Pivot the data to upload easily into my ovl_sushi bucket
4. The upload into my bucket has been broken down into batches of 2000 rows instead of 1 big upload. Had to do this to avoid the error "max write limit exceeded"

Let me know if you need a more parameterized script (like influx_csv.py) and I'll make the changes.

### CODE REVIEW

**Comment by mikeyrf** [comment]
@deepsp94 yea I think a more parametrized script like `influx_csv.py` would be nice here. I think it would be interesting to specify via command line flags:

- Source bucket
- Destination bucket
- Backfill start range

Along with the standard `params`, `config` setup we have going. Let me know if this works for you.

Made some small cleanup changes as well so github actions passes successfully (`flake8`)

**Comment by deepsp94** [comment]
Hey @mikeyrf, i'm working on the other issues too, just wanted to get this merged in without any conflicts. Lemme know if you get a chance to review :)

**Comment by mikeyrf** [comment]
> Hey @mikeyrf, i'm working on the other issues too, just wanted to get this merged in without any conflicts. Lemme know if you get a chance to review :)

Sounds good! Let me review real quick

**Comment by mikeyrf** [comment]
Looking great :) ... merge whenever you like

**Pull request merged**
